apiVersion: v1
metadata:
    name: berg-db-auth
    namespace: postgres-system
type: kubernetes.io/basic-auth
stringData:
    password: ENC[AES256_GCM,data:F1a2jhNM4/n1HWRAUK4uXcMHBDg6Mg==,iv:jucprGdPbhad9902KnQWxRDpRPKFpcDat/kri4Ly088=,tag:UGKgaUjxINXhCMOTCbX2bw==,type:str]
    username: ENC[AES256_GCM,data:9BTPjw==,iv:WLvVQNNuaTXlOSl8B+TfHHggmxfmAt+VnlsiD0Apztk=,tag:KtuGsLsaXfziZVaP84I6ew==,type:str]
kind: Secret
sops:
    age:
        - recipient: age15h69z4sdwl8teyzuttaldhaaadmfzmmjkvszw0ar6sdq5ryhjp3qwagxgd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBNjIvYktPZjA4MCthVGZx
            SHFDeTV5SEYrMEo3Q1VaVldqVGVxVUozdFFrCnp6YldsbkJPNFpEaTRVK2JVTU5Z
            OGFjdFU1ZENwVmVLZnd1VmhybVlkMDAKLS0tIEF0ZGNhTTd1L21QOTVJMkM3anlG
            c2hKOGRvQ2RaTWc4czFPQXR5UndCTVUK/bTiXwWb9gwMD7od4K1L1TFpSANFFm6m
            LzML+h9pQTm0umudi+v3yruyLIDNMnONaDWokBC6SOGHKTwcUc7/iA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-23T13:36:56Z"
    mac: ENC[AES256_GCM,data:389/nd/osUkLKlZbquG5JN9FnG7yxMNgOaY+4ou7+w6HE7C942BEE+N7tzlLehgtXPyiSaj+qxgogI8iFP9oPPvyB+fjjTA2tTnsCjVQAijhuyiRLMwwkvOfb7aeSeOuQou8QGwndZqv+P6C3vWKm8yWWAoikv3JKCsYWOPDHPk=,iv:H3Wg4c2UZfFjbHXsFnoGG6u6ZH/baTQ3jPHZiocwvAA=,tag:25jT0ZHJbHGA5bykiOt7kQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
