apiVersion: v1
metadata:
    name: grafana-db-auth
    namespace: postgres-system
type: kubernetes.io/basic-auth
stringData:
    password: ENC[AES256_GCM,data:6Tb0TOYjnA0cADc6VttSRmDB1pQlfw==,iv:bhemi7whKldqspZtbcgs2hnuHkN3ITEogtxje4dS/Cw=,tag:yiHMrvaW/6TdYGbNxDWpIQ==,type:str]
    username: ENC[AES256_GCM,data:MVMr3CBadA==,iv:XP3sZYRUg/jtt3tM5HoWvDrexKkH4kCS7j7IKG4XHgo=,tag:PTJxwkhOnec9QDx+TSpT2w==,type:str]
kind: Secret
sops:
    age:
        - recipient: age15h69z4sdwl8teyzuttaldhaaadmfzmmjkvszw0ar6sdq5ryhjp3qwagxgd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvN0gva1RNZmdOVTl3V2o0
            NFdYTVlCRW5YZjVTQnY3YUJ6TER4aitnM1dnCjBMYVNsUFBxc1lIQW1lNjQ5eUFt
            bG5MMWdNK1hEejlZbWN4ek1SVDQ5TW8KLS0tIDQ0UFlaZXJHOWJPaUNRTmNnWVha
            M2lGR25qWEhQay9ZZHpYYjNPakFKSlEKIdn+j2Jb0bhjzFcdQ3Fo/ffEa8Iw7d+s
            cdNTsbWp9O5qFgqj+vxXkEhfUgzgZGDe3zoihSK0p0DJgSSDh0WLBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T11:06:37Z"
    mac: ENC[AES256_GCM,data:HEXL/OK6PZcKfA+Z6QvINFtxuY/PiSa47hKWQ/8ndEX9iV7cuId1Pw9bZzkuPri8Avvs0U9Fv420fUHGYCmMUpZlJumOstaMM7E2Xxbh1XJARlT6JmBUv/g+HsX8BTiHNs2JMAO1PmYuDDy1NLm55dUEc/mwfmJYF7NMUlwQeP0=,iv:h+XVEzNO2d5U2cpZcSxXb1gAhWEt6nRnthSIJvpUd6k=,tag:FTH4BpxAAXmGMxFCcbs3HQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
