apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: metallb
  name: metallb-controller
rules:
  - apiGroups: []
    resources: ["secrets"]
    verbs: ["create", "get", "list", "watch", "delete", "patch", "update"]
  - apiGroups: []
    resources: ["bfdprofiles.metallb.io", "communities.metallb.io"]
    verbs: ["get", "list", "watch"]
  - apiGroups: []
    resources: ["bgpadvertisements.metallb.io", "bgppeers.metallb.io", "l2advertisements.metallb.io"]
    verbs: ["get", "list"]
  - apiGroups: ["metallb-controller"]
    resources: ["deployments.apps"]
    verbs: ["list"]

  # difference from upstream below
  - apiGroups: []
    resources: ["ipaddresspools.metallb.io"]
    verbs: ["get", "list", "watch", "update"]

