apiVersion: apps/v1
kind: Deployment
metadata:
  name: metro-app
  namespace: metro-app
  annotations:
    secret.reloader.stakater.com/reload: secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metro-app
  template:
    metadata:
      labels:
        app: metro-app
    spec:
      containers:
        - name: metro-app
          image: ghcr.io/kubeside/images/metro@sha256:3a08c97a2c8705bee30e7b7e2b7d7594b75b4160535ab0e4be2eb3d6d7229c5f
          ports:
            - containerPort: 80
          env:
            - name: OPNSENSE_API_URL
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: OPNSENSE_API_URL
            - name: OPNSENSE_AUTH
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: OPNSENSE_AUTH
            - name: METRO_MODULES
              value: "opnsense.js dns.js metro.js fetch_speed.js"
