apiVersion: apps/v1
kind: Deployment
metadata:
  name: metro-app
  namespace: metro-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metro-app
  template:
    metadata:
      labels:
        app: metro-app
    spec:
      containers:
        - name: metro-app
          image: ghcr.io/kubeside/images/metro:153efa82183e5299ca823d4214a1b397971cacce
          ports:
            - containerPort: 80
