apiVersion: apps/v1
kind: Deployment
metadata:
  name: metro-app
  namespace: metro-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metro-app
  template:
    metadata:
      labels:
        app: metro-app
    spec:
      containers:
        - name: metro-app
          image: ghcr.io/kubeside/images/metro:2973917a6299b8ccb789883f93ec1a4bf75c999b
          ports:
            - containerPort: 80
