apiVersion: apps/v1
kind: Deployment
metadata:
  name: metro-app
  namespace: metro-app
  annotations:
    secret.reloader.stakater.com/reload: secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metro-app
  template:
    metadata:
      labels:
        app: metro-app
    spec:
      containers:
        - name: metro-app
          image: ghcr.io/kubeside/images/metro@sha256:2f88ab747d5f48ea1f277092e8b8308695aa7067fa2831d26ff238f1b30b32d
          ports:
            - containerPort: 80
          env:
            - name: OPNSENSE_API_URL
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: OPNSENSE_API_URL
            - name: OPNSENSE_AUTH
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: OPNSENSE_AUTH
            - name: METRO_MODULES
              value: "opnsense.js dns.js metro.js fetch_speed.js"
