apiVersion: v1
kind: Secret
metadata:
    name: secrets
    namespace: metro-app
stringData:
    OPNSENSE_API_URL: ENC[AES256_GCM,data:bbF6ekSXozZSsydAf6/TK73Pu5JSrH0=,iv:XHv9t1Tc1DuMtH0L7LUWgy01ppg89qYmMLGtZ3t3xHo=,tag:WI+ck9ZuWbpq5mp0vIH5iQ==,type:str]
    OPNSENSE_AUTH: ENC[AES256_GCM,data:JqeNH0QbcCPg64zSq666/W+IzLK1YzRROO+QH2z1qc3xll1Q6zzCPh+eDewduaHTFAlgzNDl9MjYYVh0LfLYn6eY7H2YMfxLN4BWB5yAFUiS24mZMZXYkbQOSzXUxIbLnSSoXPnu9VP2qEUCjUms9LR3E4UvNunowiY+iPpCmXnCQ0vMYH2mya0pYF5a17Etfrd45YMs/5ik2t0I7yEc56dOtTumn8wXv5hTcGQFM6VdU9ojB1rs9ZGSWCGN5RQgHvjhwC7y+ayHdI0KcZ67oX4O2eWJ//GR/OOdsvsQ,iv:KuFnJae/tBP9ltQdsYhGWohKzxgxQwHnC7+e8OF86tk=,tag:IKE1k+p+M8R9RYTv73o9fw==,type:str]
sops:
    age:
        - recipient: age15h69z4sdwl8teyzuttaldhaaadmfzmmjkvszw0ar6sdq5ryhjp3qwagxgd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyeUxHUG1VaGpBZHJNaTZZ
            VmJsbWNYcjRBWlYxQ0Z5L2RHejVCdTVXRVhzCjdjRGVuSVNUdjFDVGFHdlMzSSsz
            c2F5RVI1dlFsNzhsUGsvVm1SVjZoNncKLS0tIE0wL2JBZFVMcm1PSmRhUzN1YXBS
            V2QzaC9iNThuaDdSME9lWC9QMGhxeVEK+wNir3Ucl4HDrxYyTnAxlNdhlkmjPWe5
            UNV0gXbyS9bqB13mma5ZrTOKTyMfTihHV+aAkj2eWNOrCNUgEtd7NA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-24T12:47:02Z"
    mac: ENC[AES256_GCM,data:MjPEIdLahVonEHX5vm9Pns+WrJ6KfrPpsZcU1Io8Za63MlWVhXIlANwvUd9WqdGs7aV4YJp0u2nkq576jsNxVJnuKqWJoSUYNGF9gJncOVP4Ef4JR7Zb387wET+1HdSEJh2ayDNZUBh0F/NRM4OtttbGOEVevwS992YXpcbUAtA=,iv:AvSDIC+mjQw6EnyiXx9ZKgSF9oxDKl6E6fEKjfIE/vA=,tag:d5UJz+ODF6xzB9Zy3vsVEA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
