apiVersion: v1
kind: Secret
metadata:
    name: secrets
    namespace: metro-app
stringData:
    OPNSENSE_API_URL: ENC[AES256_GCM,data:zTWc10W+KD3FZflQb9AVp0K4PitEAUY=,iv:9CGMg2B+RJXnq0Cvz3dzWDZteo57FOCxs/twcXsf7Ws=,tag:YOa3hiRZRjhF+nLpAX8FjA==,type:str]
    OPNSENSE_AUTH: ENC[AES256_GCM,data:n5yY3kUKyAKnoQb7g3hQlbo5jPT6f5EJTEx6LQByh/dj9uJUVDte4XL1uZGGXN4yuBFuhBUVdwBC7sBf+ixU3oRLAYQFKYXrPK7IQwzC/WhrIM8Wxxn6p/jQ8gAkwWGogt8/rUOoSnUrlnDDjstMhlCOCY3vWuzoJwAq88RZiFaXkGtzdFbCM4OpstZbw6/sQlBqSxBeYGLa3Jlk1Ss+YhZrwAqTwU3q90aBwmy3lX2brr7PT/hxVKwMd6kVjfAy65C9BX3RBbkno3rPyoNtdWC21FpLGN/5XPrCGuxf,iv:rdzQ2vr143O1O20hPcNkbcQF5Q7H1dyHNGFO6Hf7VgI=,tag:cwhmZie2OuIsLyeTCUDDGw==,type:str]
sops:
    age:
        - recipient: age15h69z4sdwl8teyzuttaldhaaadmfzmmjkvszw0ar6sdq5ryhjp3qwagxgd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpWjVjRmZmTzVuZXRMTXFD
            dGtBb1FmWjRrNkk4Ukdpd2tpeXpFZEJxWGxnCmNqdVVQL2pyS0hiOVZ3Ni9ma2Jk
            ZWU4UVRjZFdKK0hCSWdsVEp5UFA3WjQKLS0tIFRuMFBCYTIyZkNKd0RhMnRvUXYv
            Z1ErVUpGWTZxSnFMbHNrK2tUcUlYSlEKsxPkKLFfy+U8O8jgTzMB5mwfi/u3I8TT
            8/ZhQvNJ4HxA/MyuA+5Ha1dx5vWgVVxXVz0GxsHFvasW/Dr6iSGy8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-24T12:40:08Z"
    mac: ENC[AES256_GCM,data:yvbTZpT+68oHSHfafYKpKO6b81LrIzTfFGMutHQ4jmU8neq/V1P22MYeL01f9CeV8jdKXIEY2RF0MZSHUTiVLpoMZJXLf2Uiwqwh1NM9YglTzV+LUTC5xCOwXgcsNbKSyNNqH8vB4WR5JA9nqPlTLl5+fuCpJAV72wz4JhS6qFs=,iv:E4DJx5fD7bR9rRTBkRfs3Rv5MMeHHwFr/xApKOdY4ts=,tag:YL3gTi5n8U8Psc/8Apa6PQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
