apiVersion: v1
kind: Secret
metadata:
    name: secrets
    namespace: metro-app
stringData:
    OPNSENSE_API_URL: ENC[AES256_GCM,data:dA5X94Zu29YI7JZPACcuSbCX3lv/Uj8=,iv:+KQw+1ZL/3WRnVPkd1RuJJLHn+wM8ETMlo0fhe83QWY=,tag:ZZ+mkbFNq/6+EfWzu2wUVA==,type:str]
    OPNSENSE_AUTH: ENC[AES256_GCM,data:i+aDFg7QjrjifMg9RfGJl9HQzgU6gzvVkuvGrN/N69HHP7y/KsjAz5wY2EM5DuMWnOkx6kXL0l26krftLJjItecxaGR723UWhPO4a9kacFtGZRZclBKPFC4FRUM8fsCn/YJYHa/fZg5JpprzsiQJOPTNRaEfugoqcZun67+XFilA1MSaZJQpZ2lugxIQC7uX/rSnN9RsPAQ0J0UhiKIwhEVPRvODRxlG6hr6h2REqR8K6KKl9Zi66LqTZUbXe5zJ3WKvCHLq+Mmy9mYqwcielo5irYAHv1/ZfGbZtTmc,iv:Gc4+cgYKh7VHHsOtGBucaDgYRTsZU08rjlrt8CtFE4c=,tag:UCPllHBcIdL63IiNxU0XPA==,type:str]
sops:
    age:
        - recipient: age15h69z4sdwl8teyzuttaldhaaadmfzmmjkvszw0ar6sdq5ryhjp3qwagxgd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6OVBaWjQwdmF6WCt4REZQ
            QU42ejZ5U3RPWDdqa1lVdlJvbi9LMTlKR1F3ClcyRFF4Q1NKbUNMWHVnMXNFb1Mz
            SlMxTUNRVGp6YVQyQ2dKWWYrWU0yeWMKLS0tIExOTXdiMzNvZE56MDEwQVdPTFJN
            ZTZFZm05S1RiLy9TOWloMVdVRFRuN1UKkjDchL5Qhq6CinkccKujPvy4I5mYQxEk
            JOw3R4yZUhwC16B9czTP8syeIBacCLapzY/m4BY7np1PetM+E3RFIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-24T11:41:54Z"
    mac: ENC[AES256_GCM,data:rkDHGoC88vSfrXT1dnfSlpdvsUQPd/ZUNh8iXK284LsoCMyQWlcj6gmWoBVKuOC8JdB4+ONwJ/aoEnaox/1AsaQGmGCJjkt1TZvvJHFDvlPGJlRoKhBpgH0uhcjMEwuh1DwMhPCXBK/b89lmSNL19447GeG8X8PBTnZUVgNUrr4=,iv:0cmoCTSjTckAH6K417O9KGklpBGGv/jOCPIap2uUIS0=,tag:GJ/RFe3GpxrkAHxzqbNbYQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
