apiVersion: v1
kind: Secret
metadata:
    name: domeneshop
    namespace: cert-manager-system
stringData:
    APIToken: ENC[AES256_GCM,data:FJJ+J/+ExE4k7ro5mm58Tg==,iv:W6Fg7gGwqopOnFA4l24eJZ+AbSKjYMDsbL9nGk34+EI=,tag:EVipexSyu/zn71LATy7scg==,type:str]
    APISecret: ENC[AES256_GCM,data:Urja07cmP8uSBGMCYCiNfOmgC7W9Y03vZdYj1rJdyZfEs8ACD4eJjym8NwpLVgFLzF9ysf7zn3mSEbSKCVmJlg==,iv:yPxMgu3eo8wS0SqLGIp9HYBp5G40+lZTgHuXBuKR7I8=,tag:bFTqAhsS3lCdnHUWdw3Haw==,type:str]
sops:
    age:
        - recipient: age15h69z4sdwl8teyzuttaldhaaadmfzmmjkvszw0ar6sdq5ryhjp3qwagxgd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLck1PSXppNVh4MnV1elRW
            Nmxxa0ptbktWWndJRWlRa2tLSUhLVnpaelFNCnFkY2hRL0kxT3dzMEVLd2pORVRm
            OVVVZ2EwWHplYklCbEhVQkdJNlg0QVkKLS0tIDE2UHMrSHU4cEE2VSttUjFzRWNM
            N2NYWEpIbGt5dWxWMStPNThVK084cVkK/5D05ZYk38PRam+nmTp/yPK0A2F3ftf1
            2Tm4EnDumoEt+46Gr55gsrzxZAtuNFlyPQ7R65zxUoQqUBvcTN4bBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T12:46:15Z"
    mac: ENC[AES256_GCM,data:gZd40kH7FUxjta7Cd8qLNlbXZxXRBmtl0Sm2rvWPcYEa1dyRWVjsKvxLWjpx4wtE7R6FmXa1+hCViGDIfUFdW0P4lxCAsw5Bz/YE6nMZ5JuWtTC4fMdcy4l0SPHlSNFOmJWHwFSLEDCeGf+vQTRyf/FnJcaxugf9lmiWI8UDWog=,iv:voED7xI5IJPyPoJ3EeXC2m0WLwBr8aHRJqwFW0XOdUQ=,tag:/P0dPejX9kE+2WGY7udCyw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
