apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: domeneshop-issuer
  namespace: cert-manager-issuer-system
spec:
  chart:
    spec:
      chart: cert-manager-webhook-domeneshop
      sourceRef:
        kind: HelmRepository
        name: domeneshop
      version: 1.0.0
  interval: 1m0s
  values:
    groupName: api.domeneshop.no
