apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: smb
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: smb.csi.k8s.io
parameters:
  source: //filserver.school.arpa/Kubernetes

volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  #- dir_mode=0777
  #- file_mode=0777
  #- uid=1001
  #- gid=1001
  #- noperm
  #- mfsymlinks
  - cache=strict
  - noserverino # required to prevent data corruption
