apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: lars-media-app
data:
  config.json: |
    {
      "activities": [
        {
            "type": "video",
            "path": "static/a.mp4"
        },
        {
            "type": "image",
            "source": "static/Skjermbilde 2025-03-27 - 1.png",
            "duration": 5000
        },
        {
            "type": "image",
            "source": "static//Skjermbilde 2025-03-27 - 2.png",
            "duration": 5000
        },
        {
            "type": "image",
            "source": "static//Skjermbilde 2025-03-27 - 3.png",
            "duration": 5000
        },
        {
            "type": "image",
            "source": "static//Skjermbilde 2025-03-27 - 4.png",
            "duration": 5000
        },
        {
            "type": "video",
            "path": "static/Basket.MOV"
        },
        {
            "type": "image",
            "source": "static/Borg.png",
            "duration": 5000
        },
        {
            "type": "image",
            "source": "static/Lysmaling.jpg",
            "duration": 5000
        },
        {
            "type": "web",
            "source": "https://pent.no/59.74389,10.20449",
            "duration": 10000
        },
        {
            "type": "video",
            "path": "static/Teaser.mov"
        },
        {
            "type": "web",
            "source": "https://tavla.entur.no/EsmjKCakCorshCFoWVRm",
            "duration": 15000
        }
      ]
    }
