apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: iso-cache-app
data:
  config.json: |
    {
      "cache_targets": [
        {
          "url": "https://releases.ubuntu.com/24.04/ubuntu-24.04.2-desktop-amd64.iso",
          "file_name": "ubuntu-24.04.2-desktop-amd64.iso"
        },
        {
          "url": "https://releases.ubuntu.com/20.04/ubuntu-20.04.6-desktop-amd64.iso",
          "file_name": "ubuntu-20.04.6-desktop-amd64.iso"
        }
      ]
    }
