# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: persistent-cache
#   namespace: iso-cache-app
# spec:
#   resources:
#     requests:
#       storage: 20Gi
#   accessModes:
#     - ReadWriteMany
