apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: minecraft
  namespace: minecraft-app
spec:
  blocks:
    - cidr: 10.4.0.50/32
  serviceSelector:
    matchLabels:
      io.kubernetes.service.namespace: "minecraft-app"

