apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft
  namespace: minecraft-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      nodeSelector:
        kubernetes.io/hostname: talos-n04-lex
      containers:
        - name: minecraft
          image: itzg/minecraft-server@sha256:730bebfb27fa17e0d5ed0315bf47eb50b4f90a746e199409268534b15cfbadc4
          ports:
            - containerPort: 25565
            - containerPort: 24454
          env:
            - name: EULA
              value: "true"
            - name: TYPE 
              value: "neoforge"
            - name: VERSION
              value: "1.21.1"
            - name: UID 
              value: "0"
            - name: GID
              value: "0"
            - name: MODRINTH_PROJECTS
              value: |
                resourceful-config:lSbyRD6v
                create-ultimate-factory:AEMRNsNS
                create-renewable-brass:Nlbe2Hef
                accessories:Fb55Fgjz
                netherportalfix:O09BGtgh
                create-integrated-farming:FlSODr7U
                create-tfmg:uDi14nbt
                xaeros-world-map:XwL25au3
                cobblemon-pokenav:yCSofpNb
                bellsandwhistles:w0mifib8
                notenoughrecipebook:8SBaRv1t
                quick-pack:A5J7bhL4
                create-track-map-(unofficial-fork):EYyY9A0V
                create-sifting:hk3kHwCT
                rctmod:qyxrdzND
                cobblemon-spawn-notification:c1PTZDb2
                escalated:kEo89EkW
                scholar:p8et3u1j
                cobblefurnies:g6YTiF66
                create-renewable-egapples:1kUBuEx8
                fazs-roleplay-clothes:urYgvUDy
                smarter-farmers-farmers-replant:odppGdXf
                cobbledollars:QSl34Qen
                fzzy-config:MAPG6cXE
                create-winery:vTUNDdDM
                create-rustic-structures:d0sTQvqS
                create-copper-zinc:1Z1LCW5Z
                overbalanced:CqxebqMo
                justsomeclothes:hQYRZvAS
                cobblepedia:dEMwrap5
                create-ratatouille-fried-delights:sTm1ZEgP
                create-prismatic-shine:gKqw2akx
                owo-lib:NMCHU6DZ
                create-sound-of-steam:iFePoN10
                create-chocolate-fountain:mBNDwtat
                supplementaries:3N4gijtd
                create-ratatouille:Ovv4xLQg
                create-bitterballen:15wUZ9Rw
                create-trainutilities:CPAbSUUg
                lithostitched:wiffJSbz
                structure-layout-optimizer:eTz03Gfd
                emi:5sIPA1To
                create-bits-n-bobs:XKDQlGJW
                create-structures-overhaul:vpYjUv75
                create-live-radio:xYQcy5uG
                neo-bee-fix:RFt9dm5Q
                create-railways-navigator:hjpv7klQ
                farmers-delight-extended:3zUEyjxn
                deployer:XrLW2FiE
                axes-are-weapons:UVPAidip
                createschematicchecker:KzTBulXV
                terrablender:6e8GCrLb
                curios:yohfFbgD
                carry-on:cgZi7nC7
                create-aeronautics:YhZLrAFC
                lodestonelib:CohX6yP1
                c2me-neoforge:bxMrYsyE
                create-sound-of-steam-tuning-wrench:eSBB1Bvs
                fazcraft:tQFPLUFJ
                create-diesel-generators:7TPYyw7R
                create-vibrant-vaults:t17qYXjn
                create-drill-drain:HCsWT6mL
                open-parties-and-claims:b16WHzyv
                puzzles-lib:EgWWSAhJ
                create-easy-structures:ECkmsrG4
                cobblemon-capture-xp:nP29aFGP
                create-stuff-additions:2RuRqjfk
                xaeros-minimap:CklXEjmp
                missingmons-cobblemon:8MaQRS0b
                sophisticated-backpacks:gCxpNA3A
                create-guardian-beam-defense:lobV4ut5
                cobblemon-mega-showdown:BAOrFYvg
                create-goggles:Co24W2FL
                connector-extras:dgLCqZyo
                yacl:7TVdVtxF
                miners-delight:YUHbwbgQ
                numismatics:guON3qvQ
                toms-storage:x8jcBWWG
                create-cardboarded-conveynience:DkktDPvc
                yungs-better-ocean-monuments:yFjEcj2g
                copycats:kecZ0sl7
                modernfix:VGmSpV69
                create-old-infrastructure:kNxg2jFz
                dragonlib:SgbO14PV
                create-threaded-trains:ry1hvo4l
                serene-shrubbery:rRJVLCOH
                create-stones:ndmghTMU
                create-rail-grinding:BmJzz9l6
                create-more-package-couriers:rv1JwLWn
                create-train-lights:suYdvEKP
                geckolib:gFmrC8Ru
                patchouli:BIogJv2D
                cosmetic-armor-reworked-forked:U6kExSSz
                yungs-api:ZB22DE9q
                emi-loot:QXkODMCT
                create-fast-schematic-cannon:e70DdjWe
                create-clothes:AaCECJnd
                create-pattern-schematics:VSJhIkG2
                railway-evolution:rIiRE1uT
                create-dragons-plus:lSnZyFnZ
                create-more-packages:QHHyVreP
                simple-netherite-horse-armor:PJ7q3Y9v
                ferrite-core:x7kQWVju
                etched:h6eJfwiW
                cobblemon-integrations:NEiILQCx
                create-garnished:w7HZbZUe
                forgified-fabric-api:7nHK7hMg
                coroutil:H2YXCYUY
                cgs:1w2BHZY6
                prickle:EE1FHDyD
                cobblemon-playerxp:MeFehG9a
                gravestone-mod:Y29z3Y9Y
                create-dreams-and-desires:bqMxf6Ua
                cerulean-advancements:i5PXO3P7
                create-aquatic-ambitions:cgOQIktB
                armor-statues:SGpwIu7v
                terralith:IY93YaEe
                create-more-parallel-pipes:aYrPugrv
                create-simulated-additions:tP7OCy3K
                create-blockchain:AZNYSImQ
                glitchcore:S2TfWrZR
                lootr:C2tLycH2
                kiwi:2flHQIzv
                netherracked:UI2l4FTm
                tm-masonry:VLRueVMY
                hypertube:MsypJ6Dy
                create-central-kitchen:kmHFmmpV
                create-tweaked-controllers:csCe2v7f
                create-netherite-additions:yosj4p3v
                create-design-n-decor:uQsIRky8
                create-renewable-netherite:qhKlkgfZ
                extended-wrenches:g0PyoRas
                sophisticated-core:616eWTaq
                architectury-api:ZxYGwlk0
                fast-paintings:PQ155hbf
                gml:IDRMIIb4
                natures-compass:nFniEtJV
                another-furniture:Q29JlZfU
                packagerspsic:e7XZY6Md
                create-access-denied:g0JvLmzZ
                createaddition:qPr8V4G2
                cobblemon-trainer-doubles:g5dqlxc7
                cobblemon-fight-or-flight-reborn:kyo4qCAc
                bookshelf-lib:1sdJl7J1
                appleskin:uAKA6Laj
                biomes-o-plenty:8vIRXPpR
                create-totem-factory:jyvlokKK
                zfastnoise:tGdbMrnn
                connector:1i8teo7m
                create-the-air-war:qRmOHGkh
                create-additional-logistics:soesZiME
                create-meta-logistics:22gj5jAT
                grapplemod-skybound:ejlIzfJ8
                mru:qYqVf5jP
                zeta:9GjNW2Gf
                create:UjX6dr61
                man-of-many-planes:onE42Qs7
                cobblemon:S1TrAn8c
                kotlin-for-forge:NrSebcsG
                cobblemon-tim-core:QQO61rRS
                cloth-config:izKINKFg
                seamless-sleep:Lw02ZJke
                create-trimmed:P1pdTwvn
                txnilib:M1CyD3Uu
                aileron:XDz1C9KI
                create-more-drill-heads:CSXCxG3F
                cobblemon-create-industries:GIGyu6Bk
                create-man-of-many-planes:7nmQy8tH
                extra-gauges:7ogQOYHA
                distracting-trims:2KEQq349
                cobblemore-library:Ypz0g6qz
                cobblemon-counter:aJArPPZ7
                ntgl:AHTujnLv
                create-contraption-terminals:XrNWi3Wo
                rctapi:zpphgptV
                mechanicals-lib:z9HvpJMU
                yungs-better-desert-temples:GQ9iNWkI
                sablecompat:Ucq7afTi
                createlazytick:Dx5cIwDo
                simple-voice-chat:6rT2RWh6
                quark:dGSYpGOo
                yungs-better-nether-fortresses:iopJiJQp
                ends-delight:YxSK1qNm
                interiors:gBrfZy6S
                create-mobile-packages:2rAbaFXC
                shatterbyte-lib:yVCCi6TK
                create-deep-dark:3tduJc4Y
                konkrete:stJDU839
                easy-anvils:fSQSKhdF
                create-steam-n-rails-1.21.1:oQKsMKfj
                createoplenty:k7AAVyW3
                ecologics:hsEfn34V
                create-let-the-adventure-begin:d3YuJ3s8
                farmers-delight:GbNuOZ4S
                reconnectible-chains:haHsKT7H
                create-structures-arise:ZFrDlvkl
                create-alloyed:mhmFlajn
                yungs-better-dungeons:D6aZn0Em
                cobblemon-smartphone:8snhY639
                create-deco:qrcMVoBD
                amendments:8xf6Wpxs
                cobbreeding:xt8IiPEN
                create-remote-terminal:H4wNS4NT
                ichunutil:OvIyyNh4
                more-sounds:s0FVNDXY
                balm:3XiinKbh
                slice-and-dice:tyVnEa75
                createfluidlogistic:JnbW4dVU
                rpl:hZ6B2Z0x
                yungs-better-strongholds:8U0dIfSM
                create-synthetic-pressure:S3pAqL5x
                updating-world-icon:qEFip2XZ
                copycats+-aeronautics-weight:wsXjRa7l
                create-more-automation:en1TN4J7
                cobblemon-unchained:I5oNveU5
                lithium:RXHf27Wv
                my-nethers-delight:qBUSJw5Z
                cobblemonextras:ZYtnELom
                trashslot:JRxmKPV9
                blocks-bogies:rUu97B0K
                cobblemon-safepastures:s58N9Vy1
                create-train-parts:UwPDQjGx
                map-atlases-forge:BlD4MEYm
                companion:xotWY5Gs
                create-enchantment-industry:QclZk1u6
                moonlight:sqbhVahR
                create-aeroworks:vsT0uzkn
                create-shuffle-filter:ifSwGuWK
                chiikawa:pR8MVcFC
                configured-defaults:HJxTPhTM
                e4mc:rXxApWSO
                create-new-beginnings:UfZFVKXQ
                explorers-compass:hIJ2Ev1Q
                sable:3FMsUjO4
                create-factory:8RgwHaKI
                simpletms-tms-and-trs-for-cobblemon:uaKfPMYS
                create-connected:iUFG9osW
                yungs-extras:N2EpMhR7
                potion-stacks:bnlB3gWi
                create-framed:1BtGyIVR
                immersive-aircraft:RkWu0N4D
            - name: MAX_MEMORY
              value: "5G"

          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
        
