apiVersion: apps/v1
kind: Deployment
metadata:
  name: netboot-app
  namespace: netboot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netboot-app
  template:
    metadata:
      labels:
        app: netboot-app
    spec:
      containers:
        - name: netboot
          image: ghcr.io/netbootxyz/netbootxyz@sha256:01f9790c197c69ad0b95d203c20a50f3cb74ded5
          ports:
            - name: tftp
              protocol: UDP
              containerPort: 69
            - name: http
              containerPort: 80
            - name: dashboard
              containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              port: http
          startupProbe:
            httpGet:
              path: /
              port: http
            failureThreshold: 60
            periodSeconds: 60
          env:
            - name: TFTPD_OPTS
              value: "--tftp-single-port"
          

      
