apiVersion: v1
stringData:
    .htpasswd: ENC[AES256_GCM,data:rvkeGL9Kll0QXR6nco3cE8Eq+cJvUsbpCn1po7oZ3hpmYf9aCwadZbI=,iv:BfjcmhPGbUCoa2P80J/+KAKOeRggFHLO1qsb97Dumsw=,tag:zrVQuo2svIzXKHlIWU2lpg==,type:str]
kind: Secret
metadata:
    name: htpasswd
    namespace: netboot-app
type: Opaque
sops:
    age:
        - recipient: age15h69z4sdwl8teyzuttaldhaaadmfzmmjkvszw0ar6sdq5ryhjp3qwagxgd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiNWlacXVqNjNEcXpWbk8r
            VDZNYUEyLzJnTnNCN1dtQW95MEU3UUZDSXk4Cm1oQ1MybU1hS1lXRTh5cmU3cHV6
            aWRDdWVzUHRVa3BCT0YzRUlqVXFBcEkKLS0tIDJFMnZRUm8rRzB1YzlVUUhGaHpx
            aEs4VWw2Uk5NOXMwQ0ZlYkYxbzFyL0EKDnwlwlKEPODEioN2TPsqzg2OM6hSHO5Y
            JxMTDfJdlhL1gskS4LH15Fos+BMbRRPNjxsbfG6YoPk4Jll/9yMRDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T12:36:09Z"
    mac: ENC[AES256_GCM,data:CsRSBZjCrj1n7z/sIoIRZPGMWiIuy6hIAmypvKPrtUJL4/JoEfBUDkVDHqUP1leuFVIj/+xX9VCOgkR+37s8lbxYDpCrbJIQlleZz8YNw1k2N0UP4xRtz3r7at8z9CnWM1OZ6XN9mUxxsM0U6y8vNyLoGFJ8Sa2tJbkyRj92XYs=,iv:x4lUp3zR9e/U1pqRiezycDKN+jXoMtYDjb0ZZMkNgZE=,tag:OVjlAiRMPfNy2DxsB4wmGA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2