apiVersion: v1
kind: Service
metadata:
  name: netboot-app
  namespace: netboot-app
spec:
  selector:
    app: netboot-app
  ports:
    - protocol: UDP
      port: 69
      targetPort: 69
      name: tftp
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: netboot-http
  namespace: netboot-app
spec:
  selector:
    app: netboot-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: content
---
apiVersion: v1
kind: Service
metadata:
  name: netboot-dash
  namespace: netboot-app
spec:
  selector:
    app: netboot-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: dashboard
