---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoy
  namespace: flux-system
spec:
  interval: 1m0s
  dependsOn:
    - name: gateways
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./manifests/envoy
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateways
  namespace: flux-system
spec:
  interval: 1m0s
  dependsOn: []
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./manifests/gateways
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 1m0s
  dependsOn: []
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./manifests/metallb
  prune: true
  wait: true
  timeout: 5m0s
