---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoy-gateway
  namespace: flux-system
spec:
  interval: 1m0s
  dependsOn: []
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./manifests/envoy/envoy-gateway
  prune: true
  wait: true
  timeout: 5m0s
