apiVersion: v1
kind: Secret
metadata:
    name: domeneshop
    namespace: cert-manager-system
type: Opaque
stringData:
    APIToken: ENC[AES256_GCM,data:liY0aqLYZTwAk/mMfBjGdQ==,iv:eDPYESNfuMfPSVqgPiVHea+HnkxxnDI8cB2SP6eiGi4=,tag:VgrB+NbJIokALhgynCjzog==,type:str]
    APISecret: ENC[AES256_GCM,data:K8/gTbg+N7qOb6naFlTrYq+XpSlBuw57G399tFwduwQO+F8abV5QMzDj+Lva5I6cjiVQPRTTtZCdyQBDJt4SoQ==,iv:KQIdCirz7evTWaryR8XbLiS0QXZsUta5H4akXrKqgP4=,tag:uUA/cEte+FitmywsgUVLyA==,type:str]
sops:
    age:
        - recipient: age15h69z4sdwl8teyzuttaldhaaadmfzmmjkvszw0ar6sdq5ryhjp3qwagxgd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsY3QyM0pkUi9KOXo2S2lM
            Y2Q3aHpHSkNJYTNLSGZOZkhrRE8zdEFxSGpJCnl4L2NGTk5nYWh1WWxybGoyS0Nt
            V1JmNFJwcUduQTM4N051c2oxVWxBcWMKLS0tIGo3cFZ3QjFLWVlRa2lqSWwyREdG
            a2tvNHJBc2FEZ0ZRWjFEdUNiVVU4R2MK9wfqokOzT+f5mNi7DyORk9YOZusLwzS7
            W6l1b+gQwNo4wyDGmbOdTRIb8f2u0+1fw5EuffJTW6GocV5feFXG4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-25T18:01:57Z"
    mac: ENC[AES256_GCM,data:PhsyaDMBuhD1rLGTfkenvkpwwBx9E7ZnvK5DO65crIz2v6pjKqnSRBVAfk7uSwNvwoRPf83Po9K+DXvPdAfVFHT9+NOcFrlk2gmUjteCC/4WnWUZI26rLHy54HIY2yVpoj1/arPXYF1j3eJF+VSFoMfmOfzddIuk174tpBqijSc=,iv:0ziF7Ymu1j9zfhy9s6RMZhK56eX8RY/TwfkSIy3oH0E=,tag:WvR19Jko6/Yb1Stkxri5vA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
