apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: artists-api
  namespace: reverse-proxy-app
spec:
  parentRefs:
    - name: http-gateway
      namespace: gateways-system
  hostnames:
    - artists-api.imavgs.no
  rules:
    - backendRefs:
        - name: artists-api
          port: 4300
---
apiVersion: v1
kind: Service
metadata:
  name: artists-api
  namespace: reverse-proxy-app
spec:
  ports:
    - protocol: TCP
      port: 4300
      targetPort: 4300
---
apiVersion: v1
kind: Endpoints
metadata:
  name: pfsense
  namespace: reverse-proxy-app
subsets:
- addresses:
  - ip: "10.0.0.124"
  ports:
  - port: 4300
    protocol: TCP

