apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: pfsense
  namespace: reverse-proxy-app
spec:
  parentRefs:
    - name: http-gateway
      namespace: gateways-system
  hostnames:
    - pfsense.imavgs.no
  rules:
    - backendRefs:
        - name: pfsense
          port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pfsense
  namespace: reverse-proxy-app
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Endpoints
metadata:
  name: pfsense
  namespace: reverse-proxy-app
subsets:
- addresses:
  - ip: "10.0.0.124"
  ports:
  - port: 4300
    protocol: TCP

