apiVersion: v1
kind: Secret
metadata:
    name: domeneshop
    namespace: cert-manager-system
type: Opaque
stringData:
    APIToken: ENC[AES256_GCM,data:wG9JaoarckbE3eHt1oki2w==,iv:r4GKbz49dzS4tuswhK2fA5hb0QHP6zNJl13uShDDDvI=,tag:mw56rnGfnnRfMlAgS8z5Nw==,type:str]
    APISecret: ENC[AES256_GCM,data:ZWBzsWnPeJ+G115PPfvEw9c5mGKEoOv24AuzJ6Zv7seS12UJW1cjEGY5HJKn+Aw3iRO7j5i3CCd88Z2gwgFsgQ==,iv:dB2puD2kSmBBAN+rzYZlujupz+LtR0zF3voHIwACkoc=,tag:sSocYW3HXdmVxH9GsKaCmg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1YWlpL1ZsZDZvSDRhQnJr
            L09nOUdUM0dEYm9idXZxc0I2VkFuOUQya1NNCmordWJZYU4vd2g4b1BxMWZacHZz
            c3NwUmorcDBWK2Q3QmpxOUtjTnhuem8KLS0tIHk3S0Rtb0VkNEVuOHMrMGNjZk1j
            UmxXMG9EUFZ3Q05TKzZRTEhoekI4ak0KxLKZ3uf86TiX5Z7/ZxkIa8kzJY9/eBpc
            vWMFu5D34JrPSr5VGtucsPSyRgC46UCJ3VISQF4I20h4rZ+VVOHH9g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15h69z4sdwl8teyzuttaldhaaadmfzmmjkvszw0ar6sdq5ryhjp3qwagxgd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-11T13:09:02Z"
    mac: ENC[AES256_GCM,data:UUyKU8+1WpAypj3FKKo60dQXXIRaLOCv1uXLlaITfEbllRR8vEW0oX7tk9bLfkqZftFAprvDAg5GKSDHwpRYXfXaoNZo3S0kt72hjqKVGAB/zlyW+16LaXzTo1M2B4o8zO+Udec6qq/0VV/0hXC/T3u6N2627bp5AOCrZ9jDWUY=,iv:ozZXPpm+KVgPsyUgC6jXW3VKTeg54O1CDAXPvxXTuxQ=,tag:PHJDqPbRe/VYOlxmkJXuPA==,type:str]
    version: 3.13.1
