apiVersion: v1
kind: Secret
metadata:
    name: database
    namespace: victoriametrics-system
stringData:
    password: ENC[AES256_GCM,data:ibmgzJ/Xf9y8dIvDapOz1xd64XiBlg==,iv:yS7EBXtSa2cRuaRXUrCmUrizd17FJiVoenspo9k+hJ4=,tag:sstmYGRzW12c9GqFEhBcWw==,type:str]
sops:
    age:
        - recipient: age15h69z4sdwl8teyzuttaldhaaadmfzmmjkvszw0ar6sdq5ryhjp3qwagxgd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQenlzZkNWczRzVkZxN2g4
            ckduRi9Nb1hUMFVQQVYweHl2b0luNGxad1VJCno3QVBhV29FQXUrVXI4MjBlWjF3
            TXMvcEJwSDc5MTkxNW8reEtqWmFTdGsKLS0tIFJjcCt1d043Y3NqTWpsamNvVTR5
            czBvdmlzZXBacS9Nb2w4dGd1WkZMMTQKJBBMDt6nh44j/eejbz28tUFmCt22aW/j
            nS43kK6CemuJaD599o6LxndByohhQaWpYXfIB3LEwLs80JTG+W5nIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T11:26:41Z"
    mac: ENC[AES256_GCM,data:apwphgM/xuPGq+3oCTTptq383YjegeD9U2lIG7cSJdCJbhoZbqDVmtbSu6Yiw6TuhCVA6mQDXJNXnmeQlIOUwLu3natdESnuHXXKElA+EDSbPfLloG1NXH9CZTFIMCo3hffnE6qPGZ4dFs6QBytDJeNQ9SNEzLy3tyE8v8ZO+rU=,iv:oTf9qiYnkeRWqNUs50LUCamjsBcNP3RlpQjFmpG8YiI=,tag:WQD0f0dPi+oGBYH5yUm+8Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
