apiVersion: v1
kind: Secret
metadata:
    name: database
    namespace: victoriametrics-system
stringData:
    password: ENC[AES256_GCM,data:rqjo+kGDiQ/8ZT1Umui7T3+6Nay3fQ==,iv:rVSBg7Cgf6P5RPLALGer9lgIozEa4lEaBH7VZ345f0o=,tag:syx3O6L6HSD8itRSftIIxw==,type:str]
sops:
    age:
        - recipient: age15h69z4sdwl8teyzuttaldhaaadmfzmmjkvszw0ar6sdq5ryhjp3qwagxgd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6ampabGMwQ1JRd0ZCT0Jr
            ZnV3RDAyWmsxUmk3c2luTWhiUkJQajNDQlZ3CitFYU9FZVMwdldUTWNlcDdLcmo3
            QkJlOHByeHVCOGNiNStiTzF5OTBLVkkKLS0tIGwvUjlIWUFqaGFPQnlaYmkvZDVj
            Z3UydjhCKzgrQ1RNSlZVaGIvT0o0cGMK3/QHBk6N7RItai1Xqltvf/EFQ508HgQy
            U3Xq81bIpQ1u1hx+rThnNRoZEUidAw3IqSDYhMyJEKCUhA0SZG+xag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T11:32:34Z"
    mac: ENC[AES256_GCM,data:CY+BJvYJqDzd9hsszk2hhdF5/2CEtaFkJtidbJoNWL+HIqhhMr1eTibmUZZJQzv6mObwirVn6TZ6WncLnJFt55pOY4fdkOfeEu0/6T7gU7A3vkPROezV7PMsAu4/F6ax9//IqTgzYjJjxpB3aMR/kzNQOAG7HVnvkQomvvd6QHA=,iv:ycCZcLjP9F4+HsdXi1BQ/HZlIjtCclslbILTs91kwZ4=,tag:LT5ZDG8JOdOa6UiHRnsIbA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
