apiVersion: v1
kind: Secret
metadata:
    name: grafana
    namespace: victoriametrics-system
stringData:
    GF_DATABASE_PASSWORD: ENC[AES256_GCM,data:2KYhYmzrqTkNAn56rDTAH6yLctSMtw==,iv:TSc5kvMFd22BXUvH1Y8YgJ0gPouy7NSZVTGX9mdW0RY=,tag:OUKTC95i8ilb/c0/lS1QhA==,type:str]
    GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:FROdh6U8W4sa87COb1z80zaGbX4=,iv:pBCVkJA6x9hj/7JpgSauQkamB2OY08BACIZzH+hOR/c=,tag:bwgzaDrQJXlOmXG5PVSXNw==,type:str]
sops:
    age:
        - recipient: age15h69z4sdwl8teyzuttaldhaaadmfzmmjkvszw0ar6sdq5ryhjp3qwagxgd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIdTZLaElHUFlHbHhoVHNU
            M2NaaHpJeXQrVGNvaDB1aTR5Q2xUR1hWRFNjCnNwK3RxUXI1UmxDaWhPdDdHUnJw
            RHArTzZzdU9OTElDUWFxWFYxZE11TFkKLS0tIHdpL2phMEU5b2haSmRhdlMzQnJQ
            RVdZcDdBbDVZdC9TYmtEVHJLVk04ZEEKKaEwLjDgwPrhICLtGwMgzXObo+MKawVc
            RmpVpDmMvy4j0+xYHKp8kMZ9n4+QljRr+O3n9Wrkr2xGJ5hv0E9Geg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-11T06:38:06Z"
    mac: ENC[AES256_GCM,data:AIV1c+XhqSWJ4Wc7i+VR9iydnBYqBjKXHZDRHjhFIzYA9/bs5RcifUHxQJGLgLjX+BQic0DQj9r5TgQ6iItGeoaYa4Z2B1lLAvXa+Y9/2auqhZ9FMXUeE+Ov9XWW+ViNien1IdiiJzEadOUKas205WAqJTfub9wGdZNsZjGXXr4=,iv:CgyjxLQAqYOQ1KuuXG0ZWdVLzzAhtrLXtoYpxbFpPsY=,tag:wnohV/TGNNmX3xpYw+kBhQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
