apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: victoriametrics
  namespace: victoriametrics-system
spec:
  interval: 1m0s
  url: https://victoriametrics.github.io/helm-charts/