apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: operator
  namespace: victoriametrics-system
spec:
  chart:
    spec:
      chart: victoria-metrics-k8s-stack
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: victoriametrics
  interval: 1m0s
  values:
    # causes helm upgrade failure
    admissionWebhooks:
      certManager:
        enabled: false
    victoria-metrics-operator:
      admissionWebhooks:
        enabled: false
        certManager:
          enabled: false
    vmsingle:
      spec:
        retentionPeriod: "7d"
        resources:
          limits:
            memory: 3Gi
          requests:
            memory: 256M
        storage:
          resources:
            requests:
              storage: 8Gi
    grafana:
      enabled: true
      grafana.ini:
        database:
          type: postgres
          host: postgres-cluster-rw.postgres-system
          name: grafana
      route:
        main:
          enabled: true
          hostnames:
            - grafana.k8s.imavgs.no
          parentRefs:
            - name: http-gateway
              namespace: gateways-system
  valuesFrom:
    - kind: Secret
      name: database
      valuesKey: password
      targetPath: grafana.grafana\.ini.database.password
