---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoy-system
  namespace: systems
spec:
  interval: 1m0s
  dependsOn:
    - name: gateways-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./manifests/system/envoy
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateways-system
  namespace: systems
spec:
  interval: 1m0s
  dependsOn: []
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./manifests/system/gateways
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-system
  namespace: systems
spec:
  interval: 1m0s
  dependsOn:
    - name: ip-pools-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./manifests/system/metallb
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ip-pools-system
  namespace: systems
spec:
  interval: 1m0s
  dependsOn: []
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./manifests/system/ip-pools
  prune: true
  wait: true
  timeout: 5m0s
