apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./route.yaml
  - ./backend/network-policy.yaml
  - ./backend/secret.sops.yaml
  - ./backend/service.yaml
  - ./backend/deployment.yaml
  - ./frontend/network-policy.yaml
  - ./frontend/config.yaml
  - ./frontend/service.yaml
  - ./frontend/deployment.yaml
